[package]
name = "rust-csv-128"
version = "0.1.0"
authors = ["ian-hamlin <ian@ihamlin.co.uk>"]
edition = "2018"

[dependencies]
csv = { git = "https://github.com/ian-hamlin/rust-csv" }
serde = "1.0"
serde_derive = "1.0"